import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    // Override Tailwind's default theme completely for the specified properties
    colors: {
      transparent: "transparent",
      current: "currentColor",
      canvas: "var(--color-bg-canvas)",
      surface: "var(--color-bg-surface)",
      "surface-raised": "var(--color-bg-surface-raised)",
      "surface-hover": "var(--color-bg-surface-hover)",
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      muted: "var(--color-text-muted)",
      "on-accent": "var(--color-text-on-accent)",
      subtle: "var(--color-border-subtle)",
      strong: "var(--color-border-strong)",
      "accent-primary": "var(--color-accent-primary)",
      "accent-secondary": "var(--color-accent-secondary)",
      success: "var(--color-success)",
      warning: "var(--color-warning)",
      danger: "var(--color-danger)",
      info: "var(--color-info)",
      focus: "var(--color-focus-ring)",
      overlay: "var(--color-overlay)",
    },
    fontFamily: {
      display: "var(--font-display)",
      ui: "var(--font-ui)",
      data: "var(--font-data)",
    },
    fontSize: {
      "display-xl": ["var(--text-display-xl)", "var(--line-height-display-xl)"],
      "display-lg": ["var(--text-display-lg)", "var(--line-height-display-lg)"],
      "heading-lg": ["var(--text-heading-lg)", "var(--line-height-heading-lg)"],
      "heading-md": ["var(--text-heading-md)", "var(--line-height-heading-md)"],
      "heading-sm": ["var(--text-heading-sm)", "var(--line-height-heading-sm)"],
      "body-lg": ["var(--text-body-lg)", "var(--line-height-body-lg)"],
      "body-md": ["var(--text-body-md)", "var(--line-height-body-md)"],
      "body-sm": ["var(--font-size-body-sm)", "var(--line-height-body-sm)"],
      label: [
        "var(--text-label)",
        {
          lineHeight: "var(--line-height-label)",
          letterSpacing: "0.02em",
          fontWeight: "var(--font-weight-medium)",
        },
      ],
      "data-lg": ["var(--text-data-lg)", "var(--line-height-data-lg)"],
      "data-md": ["var(--text-data-md)", "var(--line-height-data-md)"],
      "data-sm": ["var(--text-data-sm)", "var(--line-height-data-sm)"],
    },
    fontWeight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
    },
    spacing: {
      0: "var(--space-0)",
      1: "var(--space-1)",
      "1.5": "var(--space-1\\.5)",
      2: "var(--space-2)",
      "2.5": "var(--space-2\\.5)",
      3: "var(--space-3)",
      4: "var(--space-4)",
      5: "var(--space-5)",
      6: "var(--space-6)",
      8: "var(--space-8)",
      10: "var(--space-10)",
      12: "var(--space-12)",
      14: "var(--space-14)",
      16: "var(--space-16)",
      20: "var(--space-20)",
      24: "var(--space-24)",
      32: "var(--space-32)",
      "hit-area": "var(--hit-area-min)",
      "control-sm": "var(--control-box-sm)",
      "control-md": "var(--control-box-md)",
    },
    borderRadius: {
      none: "var(--radius-none)",
      sm: "var(--radius-sm)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      full: "var(--radius-full)",
    },
    boxShadow: {
      "level-1": "var(--shadow-level-1)",
      "level-2": "var(--shadow-level-2)",
      "level-3": "var(--shadow-level-3)",
      "level-4": "var(--shadow-level-4)",
    },
    zIndex: {
      dropdown: "var(--z-dropdown)",
      sticky: "var(--z-sticky)",
      drawer: "var(--z-drawer)",
      "modal-overlay": "var(--z-modal-overlay)",
      modal: "var(--z-modal)",
      popover: "var(--z-popover)",
      toast: "var(--z-toast)",
    },
    transitionDuration: {
      fast: "var(--duration-fast)",
      base: "var(--duration-base)",
      slow: "var(--duration-slow)",
      deliberate: "var(--duration-deliberate)",
    },
    transitionTimingFunction: {
      standard: "var(--ease-standard)",
      decelerate: "var(--ease-decelerate)",
      accelerate: "var(--ease-accelerate)",
    },
    screens: {
      xs: "0px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      maxWidth: {
        "container-narrow": "768px",
        "container-default": "1200px",
        "container-wide": "1440px",
        "modal-sm": "400px",
        "modal-md": "560px",
        "modal-lg": "720px",
      },
    },
  },
  plugins: [],
} satisfies Config;
