export enum ErrorCode {
  // Validation
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Infrastructure & Internal
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',

  // External Service
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EPHEMERIS_PROVIDER_ERROR = 'EPHEMERIS_PROVIDER_ERROR',
  GEOCODING_PROVIDER_ERROR = 'GEOCODING_PROVIDER_ERROR',

  // Domain (Astrology Engine)
  DOMAIN_ERROR = 'DOMAIN_ERROR',

  // Birth Profile Domain
  INVALID_BIRTH_DATE = 'INVALID_BIRTH_DATE',
  INVALID_BIRTH_TIME = 'INVALID_BIRTH_TIME',
  INVALID_LATITUDE_RANGE = 'INVALID_LATITUDE_RANGE',
  INVALID_LONGITUDE_RANGE = 'INVALID_LONGITUDE_RANGE',
  INVALID_TIMEZONE = 'INVALID_TIMEZONE',
  INVALID_BIRTH_LOCATION = 'INVALID_BIRTH_LOCATION',
  INVALID_BIRTH_TIME_STATE = 'INVALID_BIRTH_TIME_STATE',

  // Chart Domain
  UNSUPPORTED_HOUSE_SYSTEM = 'UNSUPPORTED_HOUSE_SYSTEM',
  UNSUPPORTED_CHART_TYPE = 'UNSUPPORTED_CHART_TYPE',
  UNSUPPORTED_CELESTIAL_BODY = 'UNSUPPORTED_CELESTIAL_BODY',
  INVALID_COORDINATES = 'INVALID_COORDINATES',
  INVALID_DATETIME = 'INVALID_DATETIME',
  DATA_INTEGRITY_ERROR = 'DATA_INTEGRITY_ERROR',
}
