export enum ErrorCode {
  // Validation
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Infrastructure & Internal
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',

  // External Service
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EPHEMERIS_PROVIDER_ERROR = 'EPHEMERIS_PROVIDER_ERROR',
  GEOCODING_PROVIDER_ERROR = 'GEOCODING_PROVIDER_ERROR',

  // Domain (Astrology Engine)
  DOMAIN_ERROR = 'DOMAIN_ERROR',
}
