import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { Router } from 'express';
import swaggerUi from 'swagger-ui-express';

import { AppConfig, Environment } from '../config/env.config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function createDocsRoutes(config: AppConfig): Router {
  const router = Router();

  // Load the generated OpenAPI JSON
  // Ensure that openapi.json exists (generated by npm run generate:openapi)
  const openApiPath = path.resolve(__dirname, '../../openapi.json');

  let swaggerDocument: Record<string, unknown> | null = null;
  try {
    const fileContent = fs.readFileSync(openApiPath, 'utf-8');
    swaggerDocument = JSON.parse(fileContent);
  } catch {
    // Only warn if not in production
    if (config.NODE_ENV !== Environment.PRODUCTION) {
      // eslint-disable-next-line no-console
      console.warn('openapi.json not found. Run "npm run generate:openapi".');
    }
  }

  if (swaggerDocument) {
    // Optionally dynamically set the server URL in Swagger UI based on config
    router.use(
      '/docs',
      swaggerUi.serve,
      swaggerUi.setup(swaggerDocument, {
        customSiteTitle: 'AstroViet API Docs',
        swaggerOptions: {
          persistAuthorization: true,
        },
      }),
    );
  } else {
    router.get('/docs', (_req, res) => {
      res.send('API Documentation is not available. Please run "npm run generate:openapi".');
    });
  }

  return router;
}
